name: Semantic-Release
description: Publish a new version using semantic-release

inputs:
  github-token:
    description: GitHub access token used by semantic-release
    required: true
  node-version:
    description: Node version used to install and publish the package
    required: false
    default: "lts/*"
  npm-token:
    description: NPM access token used by semantic-release, required for type 'github-npm' and 'npm-pre'
    required: false
  type:
    description: |
      Available values are 'github', 'github-npm' and 'npm-pre'.
      'github' only creates a release on github while 'github-npm' additionally publishes an npm package.
      'npm-pre' publishes an npm package appending the current timestamp and the commit SHA to the version.
    required: false
    default: "github"

runs:
  using: composite
  steps:
    - if: ${{ !contains(fromJSON('["github", "github-npm", "npm-pre"]'), inputs.type) }}
      shell: bash
      run: echo "Invalid inputs" && exit 1
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - shell: bash
      run: npm --prefix ${{ github.action_path }} ci
    - shell: bash
      run: npm exec --prefix ${{ github.action_path }} semantic-release -- --extends ${{ github.action_path }}/release.${{ inputs.type }}.cjs
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
