name: Semantic-Release
description: Publish a new version using semantic-release

inputs:
  github-token:
    description: GitHub access token used by semantic-release
    required: true
  node-version:
    description: Node version used to install and publish the package
    required: false
    default: "lts/*"
  npm-token:
    description: NPM access token used by semantic-release, required for type 'npm'
    required: false
  type:
    description: |
      Available values are 'default' and 'npm'
      'default' only creates a release on github while 'npm' additionally publishes an npm package
    required: false
    default: "default"

runs:
  using: composite
  steps:
    - if: ${{ !contains(fromJSON('["default", "npm"]'), inputs.type) || !inputs.github-token || inputs.type == 'npm' && !inputs.npm-token }}
      shell: bash
      run: echo "Invalid inputs" && exit 1
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - shell: bash
      run: npm --prefix ${{ github.action_path }} ci
    - if: ${{ inputs.type == 'npm' }}
      shell: bash
      run: npm ci
    - shell: bash
      run: npm exec --prefix ${{ github.action_path }} semantic-release -- --extends ${{ github.action_path }}/.releaserc.branches.json --extends ${{ github.action_path }}/.releaserc.${{ inputs.type }}.json
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
